# Generated by Django 5.0.6 on 2024-06-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('character_fullname', models.CharField(default='', max_length=100)),
                ('character_nickname', models.CharField(default='', max_length=100)),
                ('character_age', models.IntegerField(default=0)),
                ('character_group', models.CharField(default='', max_length=100)),
                ('character_description', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
