# Generated by Django 5.0.6 on 2024-06-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
